//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 07:22:55 AM GMT 
//


package uk.co.isbn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="M-Message">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ON-OrderNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CN-ClientName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CD-ClientDetails">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FN-FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LN-LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="A-Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="C-County" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mMessage"
})
@XmlRootElement(name = "ML-MessageList")
public class MLMessageList {

    @XmlElement(name = "M-Message", required = true)
    protected MLMessageList.MMessage mMessage;

    /**
     * Gets the value of the mMessage property.
     * 
     * @return
     *     possible object is
     *     {@link MLMessageList.MMessage }
     *     
     */
    public MLMessageList.MMessage getMMessage() {
        return mMessage;
    }

    /**
     * Sets the value of the mMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLMessageList.MMessage }
     *     
     */
    public void setMMessage(MLMessageList.MMessage value) {
        this.mMessage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ON-OrderNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CN-ClientName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CD-ClientDetails">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FN-FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LN-LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="A-Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="C-County" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "onOrderNo",
        "cnClientName",
        "cdClientDetails"
    })
    public static class MMessage {

        @XmlElement(name = "ON-OrderNo", required = true)
        protected String onOrderNo;
        @XmlElement(name = "CN-ClientName", required = true)
        protected String cnClientName;
        @XmlElement(name = "CD-ClientDetails", required = true)
        protected MLMessageList.MMessage.CDClientDetails cdClientDetails;

        /**
         * Gets the value of the onOrderNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getONOrderNo() {
            return onOrderNo;
        }

        /**
         * Sets the value of the onOrderNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setONOrderNo(String value) {
            this.onOrderNo = value;
        }

        /**
         * Gets the value of the cnClientName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCNClientName() {
            return cnClientName;
        }

        /**
         * Sets the value of the cnClientName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCNClientName(String value) {
            this.cnClientName = value;
        }

        /**
         * Gets the value of the cdClientDetails property.
         * 
         * @return
         *     possible object is
         *     {@link MLMessageList.MMessage.CDClientDetails }
         *     
         */
        public MLMessageList.MMessage.CDClientDetails getCDClientDetails() {
            return cdClientDetails;
        }

        /**
         * Sets the value of the cdClientDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link MLMessageList.MMessage.CDClientDetails }
         *     
         */
        public void setCDClientDetails(MLMessageList.MMessage.CDClientDetails value) {
            this.cdClientDetails = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FN-FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LN-LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="A-Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="C-County" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fnFirstName",
            "lnLastName",
            "aAge",
            "cCounty"
        })
        public static class CDClientDetails {

            @XmlElement(name = "FN-FirstName", required = true)
            protected String fnFirstName;
            @XmlElement(name = "LN-LastName", required = true)
            protected String lnLastName;
            @XmlElement(name = "A-Age", required = true)
            protected String aAge;
            @XmlElement(name = "C-County", required = true)
            protected String cCounty;

            /**
             * Gets the value of the fnFirstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFNFirstName() {
                return fnFirstName;
            }

            /**
             * Sets the value of the fnFirstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFNFirstName(String value) {
                this.fnFirstName = value;
            }

            /**
             * Gets the value of the lnLastName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLNLastName() {
                return lnLastName;
            }

            /**
             * Sets the value of the lnLastName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLNLastName(String value) {
                this.lnLastName = value;
            }

            /**
             * Gets the value of the aAge property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAAge() {
                return aAge;
            }

            /**
             * Sets the value of the aAge property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAAge(String value) {
                this.aAge = value;
            }

            /**
             * Gets the value of the cCounty property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCCounty() {
                return cCounty;
            }

            /**
             * Sets the value of the cCounty property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCCounty(String value) {
                this.cCounty = value;
            }

        }

    }

}
